name: create-win-installer-builder

on:
  workflow_dispatch:

jobs:
  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'
      - run: npm install ci
      - run: npm run make-builder
      - uses: actions/upload-artifact@v3
        with:
          name: win-out
          path: dist
          retention-days: 7

          

